version: '3.0'

services:
  springboot-app:
    container_name: springboot-app
    image: springboot-app:latest
    build: ./
    expose:
      - 5000
    ports:
      - "5000:5000"
    network_mode: host
    depends_on:
      - postgres
    links:
      - postgres
      
  postgres:
    container_name: java_db
    image: postgres:latest
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
